# Generated by Django 2.2.6 on 2019-12-16 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('damage', models.CharField(choices=[('C', 'Critical Hit'), ('S', 'Super Effective'), ('N', 'Not very effective')], default='C', max_length=1)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Pokemon')),
            ],
        ),
    ]
