# Generated by Django 2.2.6 on 2019-12-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_battles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='battles',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='battles',
            name='date',
            field=models.DateField(verbose_name='battle date'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='items',
            field=models.ManyToManyField(to='main_app.Item'),
        ),
    ]
